title: Galeria Nowe Teraz
title-short: Galeria Nowe Teraz
description: "Wystawy i aukcje."

url: https://galeria.noweteraz.pl

logo: "/assets/images/logos/galeria-nowe-teraz-logo-web.png"

timezone: Europe/Warsaw

google:
  tag_manager:
    container_id: 
     
social:
  facebook: 
 
company:
  name: Fundacja Nowe Teraz
  address_street: "ul. Zielna 39"
  address_city: "Warszawa"
  address_postcode: "00-108"
  address_region: "Mazowieckie"
  address_country: "Poland"
  email: galeria@noweteraz.pl
  uri: &uri "https://galeria.noweteraz.pl"
  url: *uri
  phone: "+48574662644"
  phone_human: "574-662-644"

  
exclude:
- Gruntfile.js
- Gemfile
- Gemfile.lock
- package.json
- package-lock.json
- README*
- node_modules
- ".gitignore"

include:
- "_pages"

markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
highlighter: rouge
excerpt_separator: |2+

sass:
  sass_dir: _sass/
  style: compressed

per_page: 12
date_format: "%d-%m-%Y"

compress_html:
  clippings: all
  ignore:
    envs: development
    
plugins:
- jekyll-sitemap
- jekyll-seo-tag
  
collections:
  auction_categories:
    title: Kategorie
    output: false
  aukcje:
    title: Aukcje
    output: true
    permalink: "/:collection/:name/"
  pages:
    output: true
defaults:
  # Blog
- scope:
    path: _posts/blog
    type: posts
  values:
    category: blog
    permalink: "/:categories/:title/"
    layout: post

  # Aukcje
- scope:
    path: _posts/aukcje
    type: posts
  values:
    layout: page
    category: Aukcje
    permalink: "/:categories/:title/"       
- scope:
    path: _aukcje/henryk-dabrowski
    type: aukcje
  values:
      layout: aukcja
      category: Aukcje
      permalink: "/:collection/aukcja-henryk-dabrowski/:name/"
- scope:
    path: "assets/**/*.pdf"
  values:
    sitemap: false
- scope:
    path: ''
    type: auction_categories
  values:
    layout: page
    
    
    